apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-steps
  templates:
  - name: hello-steps
    steps:
    - - name: step1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "Step 1"}]
    - - name: step2
        template: whalesay
        arguments:
          parameters: [{name: message, value: "Step 2"}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: ["cowsay"]
      args: ["{{inputs.parameters.message}}"]
